export const tabsMock = [
  {
      "active": false,
      "audible": false,
      "autoDiscardable": true,
      "discarded": false,
      "frozen": false,
      "groupId": -1,
      "height": 873,
      "highlighted": false,
      "id": 754297097,
      "incognito": false,
      "index": 0,
      "lastAccessed": 1758809922717.437,
      "mutedInfo": {
          "muted": false
      },
      "pinned": false,
      "selected": false,
      "splitViewId": -1,
      "status": "complete",
      "title": "Quando utilizar rem, em ou pixel - DEV Community",
      "url": "https://dev.to/lazarocontato/quando-utilizar-rem-em-ou-pixel-cf0",
      "width": 1728,
      "windowId": 754297023
  },
  {
      "active": false,
      "audible": false,
      "autoDiscardable": true,
      "discarded": false,
      "frozen": false,
      "groupId": -1,
      "height": 873,
      "highlighted": false,
      "id": 754297103,
      "incognito": false,
      "index": 1,
      "lastAccessed": 1758810191857.851,
      "mutedInfo": {
          "muted": false
      },
      "pinned": false,
      "selected": false,
      "splitViewId": -1,
      "status": "complete",
      "title": "Installing Tailwind CSS with Vite - Tailwind CSS",
      "url": "https://tailwindcss.com/docs/installation/using-vite",
      "width": 1728,
      "windowId": 754297023
  },
  {
      "active": false,
      "audible": false,
      "autoDiscardable": true,
      "discarded": false,
      "frozen": false,
      "groupId": -1,
      "height": 873,
      "highlighted": false,
      "id": 754297106,
      "incognito": false,
      "index": 2,
      "lastAccessed": 1758810134073.213,
      "mutedInfo": {
          "muted": false
      },
      "pinned": false,
      "selected": false,
      "splitViewId": -1,
      "status": "complete",
      "title": "align-items - Flexbox & Grid - Tailwind CSS",
      "url": "https://tailwindcss.com/docs/align-items#stretch",
      "width": 1728,
      "windowId": 754297023
  },
  {
      "active": false,
      "audible": false,
      "autoDiscardable": true,
      "discarded": false,
      "frozen": false,
      "groupId": -1,
      "height": 873,
      "highlighted": false,
      "id": 754297130,
      "incognito": false,
      "index": 3,
      "lastAccessed": 1758810207533.265,
      "mutedInfo": {
          "muted": false
      },
      "pinned": false,
      "selected": false,
      "splitViewId": -1,
      "status": "complete",
      "title": "shadcn-ui/ui: A set of beautifully-designed, accessible components and a code distribution platform. Works with your favorite frameworks. Open Source. Open Code.",
      "url": "https://github.com/shadcn-ui/ui",
      "width": 1728,
      "windowId": 754297023
  },
  {
      "active": false,
      "audible": false,
      "autoDiscardable": true,
      "discarded": false,
      "frozen": false,
      "groupId": -1,
      "height": 873,
      "highlighted": false,
      "id": 754297133,
      "incognito": false,
      "index": 4,
      "lastAccessed": 1758810432860.692,
      "mutedInfo": {
          "muted": false
      },
      "pinned": false,
      "selected": false,
      "splitViewId": -1,
      "status": "complete",
      "title": "Vite - shadcn/ui",
      "url": "https://ui.shadcn.com/docs/installation/vite",
      "width": 1728,
      "windowId": 754297023
  },
  {
      "active": false,
      "audible": false,
      "autoDiscardable": true,
      "discarded": false,
      "frozen": false,
      "groupId": -1,
      "height": 873,
      "highlighted": false,
      "id": 754297138,
      "incognito": false,
      "index": 5,
      "lastAccessed": 1758810523793.191,
      "mutedInfo": {
          "muted": false
      },
      "pinned": false,
      "selected": false,
      "splitViewId": -1,
      "status": "complete",
      "title": "Limit table's row to show a limited amount of text (truncate) · huntabyte/shadcn-svelte · Discussion #549",
      "url": "https://github.com/huntabyte/shadcn-svelte/discussions/549",
      "width": 1728,
      "windowId": 754297023
  },
  {
      "active": true,
      "audible": false,
      "autoDiscardable": true,
      "discarded": false,
      "frozen": false,
      "groupId": -1,
      "height": 873,
      "highlighted": true,
      "id": 754297143,
      "incognito": false,
      "index": 6,
      "lastAccessed": 1758810635160.153,
      "mutedInfo": {
          "muted": false
      },
      "openerTabId": 754297138,
      "pinned": false,
      "selected": true,
      "splitViewId": -1,
      "status": "complete",
      "title": "line-clamp - Typography - Tailwind CSS",
      "url": "https://tailwindcss.com/docs/line-clamp",
      "width": 1728,
      "windowId": 754297023
  },
  {
      "active": false,
      "audible": false,
      "autoDiscardable": true,
      "discarded": false,
      "frozen": false,
      "groupId": -1,
      "height": 873,
      "highlighted": false,
      "id": 754297151111111,
      "incognito": false,
      "index": 0,
      "lastAccessed": 1758810672267.414,
      "mutedInfo": {
          "muted": false
      },
      "pinned": false,
      "selected": false,
      "splitViewId": -1,
      "status": "complete",
      "title": "chrome_tabs",
      "url": "http://localhost:5174/",
      "width": 914,
      "windowId": 754297150
  },
  {
      "active": false,
      "audible": false,
      "autoDiscardable": true,
      "discarded": false,
      "frozen": false,
      "groupId": -1,
      "height": 873,
      "highlighted": false,
      "id": 754297151,
      "incognito": false,
      "index": 0,
      "lastAccessed": 1758810672267.414,
      "mutedInfo": {
          "muted": false
      },
      "pinned": false,
      "selected": false,
      "splitViewId": -1,
      "status": "complete",
      "title": "chrome_tabs",
      "url": "http://localhost:5174/",
      "width": 914,
      "windowId": 754297150
  },
  {
      "active": true,
      "audible": false,
      "autoDiscardable": true,
      "discarded": false,
      "frozen": false,
      "groupId": -1,
      "height": 873,
      "highlighted": true,
      "id": 754297155,
      "incognito": false,
      "index": 1,
      "lastAccessed": 1758810685738.322,
      "mutedInfo": {
          "muted": false
      },
      "openerTabId": 754297151,
      "pinned": false,
      "selected": true,
      "splitViewId": -1,
      "status": "complete",
      "title": "chrome api is extension - Pesquisa Google",
      "url": "https://www.google.com/search?q=chrome+api+is+extension&oq=chrome+api+is+extension&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIICAEQABgWGB4yCAgCEAAYFhgeMggIAxAAGBYYHjIKCAQQABgKGBYYHjIICAUQABgWGB4yBwgGEAAY7wUyCggHEAAYgAQYogQyBwgIEAAY7wXSAQg4NTI5ajBqN6gCALACAA&sourceid=chrome&ie=UTF-8",
      "width": 1728,
      "windowId": 754297150
  }
]